# Generated by Django 2.1.7 on 2021-01-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_type',
            field=models.TextField(default='student'),
        ),
    ]
