# Generated by Django 2.1.7 on 2021-02-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='username',
            new_name='school_name',
        ),
    ]
