# Generated by Django 2.1.7 on 2021-01-30 09:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0016_simpleproblem_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='simpleproblem',
            unique_together={('lang_type', 'problem_type', 'problem_title', 'created_by'), ('lang_type', 'problem_type', 'problem_content', 'created_by')},
        ),
    ]
