# Generated by Django 2.1.7 on 2021-01-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('problem', '0017_auto_20210130_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleproblem',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simpleproblem',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
