# Generated by Django 2.1.7 on 2021-01-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0018_auto_20210130_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleproblem',
            name='_id',
        ),
    ]
